spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  #jpa配置
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  #多媒体文件上传配置
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

#文件上传配置
fileUpload:
  uploadPath: F:\fileUpload\
