spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mrbs?useSSL=false&useUnicode=true&characterEncoding=utf-8
    data-username: usernamea
    data-password: password
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect